import type { NextPage } from 'next';
import Head from 'next/head';
import { Footer } from '../components/Footer';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>FirePost</title>
        <meta
          content="Generated by Dino&FC"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <strong className='italic text-red-300'>FIREPOST</strong>
        </h1>

      </main>

      <Footer/>
    </div>
  );
};

export default Home;
