import { useEffect, useState } from 'react';
import Head from 'next/head';
import { Footer } from '../components/Footer';
import io from 'socket.io-client';
import { useRouter } from 'next/router'; // Import useRouter from Next.js
import styles from '../styles/Home.module.css';

const socket = io(); // Connect to the Socket.IO server

const Home = () => {
  const [photoFile, setPhotoFile] = useState<File | null>(null); // Use File instead of string
  const [isPosting, setIsPosting] = useState<boolean>(false);
  const router = useRouter(); // Initialize the router

  // useEffect to connect and disconnect socket
  useEffect(() => {
    // Connect to the Socket.IO server
    socket.on('connect', () => {
      console.log('Connected to Socket.IO server');
    });

    // Disconnect from the Socket.IO server when component unmounts
    return () => {
      socket.disconnect();
      console.log('Disconnected from Socket.IO server');
    };
  }, []);

  const handlePhotoUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      setPhotoFile(file); // Set the selected file
    }
  };

  const handlePost = async () => {
    if (photoFile) { 
      setIsPosting(true);
      const formData = new FormData();
      formData.append('file', photoFile); 
      formData.append('user_address', '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'); 

      try {
        const response = await fetch('http://localhost:8000/api/post', { 
          method: 'POST',
          body: formData,
        });
        if (response.ok) {
          // Post successful, navigate to Posts page
          router.push('/Posts');
        } else {
          console.error('Failed to post photo');
        }
      } catch (error) {
        console.error('Error posting photo:', error);
      } finally {
        setIsPosting(false);
      }
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>FirePost</title>
        <meta content="Generated by Dino&FC" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <strong className="italic text-red-300">FIREPOST</strong>
        </h1>

        {/* Upload photo button */}
        <input type="file" name="file" accept="image/*" onChange={handlePhotoUpload} />


        {/* Display uploaded photo */}
        {photoFile && (
          <div>
            <h2>Uploaded Photo:</h2>
            <img src={URL.createObjectURL(photoFile)} alt="Uploaded" className="max-w-xs max-h-xs" />
            <button
              className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-2"
              onClick={handlePost}
              disabled={isPosting}
            >
              {isPosting ? 'Posting...' : 'Post'}
            </button>
          </div>
        )}
      </main>
      <Footer />
    </div>
  );
};

export default Home;
